apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
spec:
  template:
    spec:
      containers:
        - name: frontend-dev
          envFrom:
            - configMapRef:
                name: frontend-config
            - configMapRef:
                name: frontend-app-secrets
