apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../application

namespace: development
commonLabels:
  environment: development


configMapGenerator:
  - name: frontend-config
    behavior: merge
    envs:
      - environment