apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../application

namespace: staging
commonLabels:
  environment: staging

configMapGenerator:
  - name: frontend-config
    behavior: merge
    envs:
      - environment

patches:
  - devConfigPatch.yaml
